### ISSUE TITLE
Issues with 'jq not found' and genome path

### ISSUE THREAD

**Issue by hchintalapudi** [fl-yu/CUT-RUNTools-2.0#14]
Hi,
I cloned the repository and hopefully satisfied all the software installation requirements.
I ran ```./install/validate.py config/bulk-config.json --ignore-input-output --software ``` without any errors.
But when I run:
```./run_bulkModule.sh config/bulk-config.json GATA1_D7_30min_chr11```
I get:
```
./run_bulkModule.sh: line 20: jq: command not found
./run_bulkModule.sh: line 21: jq: command not found
./run_bulkModule.sh: line 22: jq: command not found
organism_build should be one of hg38, hg19, mm10 or mm9
```
Should I download and install jq separately?
Attached is my bulk-config.json file.
[bulk-config.txt](https://github.com/fl-yu/CUT-RUNTools-2.0/files/6736430/bulk-config.txt)

Some tips appreciated, thanks!

**Comment by fl-yu** [comment]
Yes that is the issue. You configuration file seems good. jq should be installed by default in linux system but you could install it by yourself.

**Comment by hchintalapudi** [comment]
Thanks for the reply, I'm working on a cluster server and do not have sudo access.
However, I downloaded the appropriate jq executable file for linux 64 and I run it:
```
jq
jq - commandline JSON processor [version 1.6]

Usage:	/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/jq [options] <jq filter> [file...]
	/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/jq [options] --args <jq filter> [strings...]
	/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/jq [options] --jsonargs <jq filter> [JSON_TEXTS...]

jq is a tool for processing JSON inputs, applying the given filter to
its JSON text inputs and producing the filter's results as JSON on
standard output.

The simplest filter is ., which copies jq's input to its output
unmodified (except for formatting, but note that IEEE754 is used
for number representation internally, with all that that implies).

For more advanced filters see the jq(1) manpage ("man jq")
and/or https://stedolan.github.io/jq

Example:

	$ echo '{"foo": 0}' | jq .
	{
		"foo": 0
	}

For a listing of options, use /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/jq --help.
```
And I added the path of this jq to my ~/.bashrc file.
But when I run ``` ./run_bulkModule.sh config/bulk-config.json GATA1_D7_30min_chr11 ``` I get the same error:
```
./run_bulkModule.sh: line 20: jq: command not found
./run_bulkModule.sh: line 21: jq: command not found
./run_bulkModule.sh: line 22: jq: command not found
organism_build should be one of hg38, hg19, mm10 or mm9
```

**Comment by fl-yu** [comment]
I wonder if you run separately on compuational node. Can you try to add jq to PATH in your summited script using something like `export PATH=/path/to/jq:"$PATH"`

**Comment by hchintalapudi** [comment]
I'm actually not queueing it any scheduling script, just running the command on command line.
You mean add the export command in ./run_bulkModule.sh?
Thanks!

**Comment by hchintalapudi** [comment]
I changed jp to absolute path/jq and the pipeline runs finally!
But the exampledata sample fails and so does my sample.
Please see below:
```
(cutruntools2) [f0042dk@discovery7 CUT-RUNTools-2.0]$ ./run_bulkModule.sh config/bulk-config.json SL_04_S4            
==================================== Bulk data analysis pipeline will run ==============================================================
## Input FASTQ folder:            /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/human
## Sample name:                   SL_04_S4
## Workdir folder:                /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/SL_04_S4
## Experiment name:               SL_04_S4
## Experiment type:               CUT&RUN
## Reference genome:              hg38
## Spike-in genome:               FALSE
## Spike-in normalization:        FALSE
## Fragment 120 filtration:       TRUE
=================================================================================================================================
[info] Input file is SL_04_S4_R1_001.fastq.gz and SL_04_S4_R2_001.fastq.gz
Wed Jun 30 16:39:16 EDT 2021
[info] Trimming file SL_04_S4 ...
Wed Jun 30 16:39:16 EDT 2021
[info] Second stage trimming SL_04_S4 ...
Wed Jun 30 17:34:19 EDT 2021
[info] Aligning file SL_04_S4 to reference genome...
Wed Jun 30 17:59:37 EDT 2021
[info] Bowtie2 command: --dovetail --phred33
[info] The dovetail mode is enabled [as parameter frag_120 is on]
[main_samview] fail to read the header from "-".
[info] FASTQ files won't be aligned to the spike-in genome
[info] Filtering unmapped fragments... SL_04_S4.bam
Wed Jun 30 17:59:38 EDT 2021
[main_samview] fail to read the header from "/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/SL_04_S4/aligned/SL_04_S4.bam".
[info] Sorting BAM... SL_04_S4.bam
Wed Jun 30 17:59:38 EDT 2021
INFO	2021-06-30 17:59:40	SortSam	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    SortSam -INPUT sorted/SL_04_S4.step1.bam -OUTPUT sorted/SL_04_S4.bam -SORT_ORDER coordinate -VALIDATION_STRINGENCY SILENT
**********


17:59:42.439 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CUT-RUNTools-2.0/install/picard-2.8.0.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Jun 30 17:59:42 EDT 2021] SortSam INPUT=sorted/SL_04_S4.step1.bam OUTPUT=sorted/SL_04_S4.bam SORT_ORDER=coordinate VALIDATION_STRINGENCY=SILENT    VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Jun 30 17:59:42 EDT 2021] Executing as f0042dk@discovery7.hpcc.dartmouth.edu on Linux 3.10.0-1160.11.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_292-b10; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.21.7-SNAPSHOT
INFO	2021-06-30 17:59:42	SortSam	Finished reading inputs, merging and writing to output now.
[Wed Jun 30 17:59:42 EDT 2021] picard.sam.SortSam done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=83165184
[info] Marking duplicates... SL_04_S4.bam
Wed Jun 30 17:59:43 EDT 2021
[info] Removing duplicates... SL_04_S4.bam
Wed Jun 30 17:59:48 EDT 2021
[info] Filtering to <120bp... dup.marked and dedup BAMs
Wed Jun 30 17:59:49 EDT 2021
[info] Creating bam index files... SL_04_S4.bam
Wed Jun 30 17:59:49 EDT 2021
[info] Reads shifting 
Wed Jun 30 17:59:49 EDT 2021
[info] Your data won't be shifted as the experiment_type is specified as CUT&RUN... 
[info] Peak calling using MACS2... SL_04_S4.bam
[info] Logs are stored in /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/SL_04_S4/logs
Wed Jun 30 17:59:49 EDT 2021
[info] Peak calling with BAM file with NO duplications
[info] macs2 narrow peak calling
[info] macs2 broad peak calling
[info] Getting broad peak summits
Traceback (most recent call last):
  File "/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CUT-RUNTools-2.0/install/get_summits_broadPeak.py", line 14, in <module>
    f = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: '/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/SL_04_S4/peakcalling/macs2.broad/SL_04_S4_peaks.broadPeak'
[info] SEACR stringent peak calling
Traceback (most recent call last):
  File "/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CUT-RUNTools-2.0/install/change.bdg.py", line 12, in <module>
    f = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: '/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/SL_04_S4/peakcalling/seacr/SL_04_S4_treat_pileup.bdg'
Calling enriched regions without control file
Proceeding without normalization of control to experimental bedgraph
Using stringent threshold
Creating experimental AUC file: Wed Jun 30 17:59:59 EDT 2021
Calculating optimal AUC threshold: Wed Jun 30 17:59:59 EDT 2021
Using user-provided threshold: Wed Jun 30 17:59:59 EDT 2021
Error in read.table(argsL$exp) : no lines available in input
Execution halted
Unable to access /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/SL_04_S4/peakcalling/seacr/SL_04_S4_treat.stringent.bed
Traceback (most recent call last):
  File "/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CUT-RUNTools-2.0/install/get_summits_seacr.py", line 14, in <module>
    f = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: '/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/SL_04_S4/peakcalling/seacr/SL_04_S4_treat.stringent.bed'
[info] Generating the normalized signal file with BigWig format... 
Wed Jun 30 18:00:01 EDT 2021
cp: cannot stat '/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/SL_04_S4/peakcalling/macs2.narrow/SL_04_S4.cpm.norm.bw': No such file or directory
cp: cannot stat '/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/SL_04_S4/peakcalling/macs2.narrow/SL_04_S4.cpm.norm.bw': No such file or directory
[info] Your bigwig file won't be normalized with spike-in reads
[info] Input file is /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CutNRun_6-18-21/SL_04_S4/peakcalling/macs2.narrow/SL_04_S4_peaks.narrowPeak
cat: SL_04_S4_peaks.narrowPeak: No such file or directory
cat: SL_04_S4_summits.bed: No such file or directory
[info] Get randomized [1000] peaks from the top [2000] peaks...
[info] Filtering the blacklist regions for the selected peak files
[info] Getting Fasta sequences
Warning: the index file is older than the FASTA file.
[info] Start MEME analysis for de novo motif finding ...
[info] Up to 10 will be output ...
Log::Log4perl configuration looks suspicious: No loggers defined at /dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/lib/site_perl/5.26.2/Log/Log4perl/Config.pm line 325.
Starting getsize: getsize random1000/MEME_SL_04_S4_shuf/SL_04_S4_summits_padded.fa 1> $metrics
/dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/libexec/meme-5.0.2/getsize: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory
getsize exited with error code 127
getsize failed me... at /dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/bin/meme-chip line 748.
[info] De Novo motifs can be found: random1000/MEME_SL_04_S4_shuf ...
[info] Loading the De Novo motifs ...
Traceback (most recent call last):
  File "/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CUT-RUNTools-2.0/install/read.meme.py", line 92, in <module>
    ss = read_summary(this_dir + "/summary.tsv")
  File "/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/CutNrun/CUT-RUNTools-2.0/install/read.meme.py", line 7, in read_summary
    f = open(n)
FileNotFoundError: [Errno 2] No such file or directory: 'random1000/MEME_SL_04_S4_shuf/summary.tsv'
[info] The signficance cutoff of Fimo scaning is 0.0005...
[info] Motif files can be found: random1000/MEME_SL_04_S4_shuf/motifs
[info] Filtering the blacklist regions for the selected peak files
[info] Getting Fasta sequences
Warning: the index file is older than the FASTA file.
[info] Scaning the De Novo motifs for each peak
ls: cannot access 'random1000/MEME_SL_04_S4_shuf/motifs': No such file or directory
[info] Output can be found: fimo.result/SL_04_S4
# 
#        Congrats! The bulk data analysis is complete!
# 
--------------------------------------------------------------------------
```
 It's stopping at the alignment step, any insights into the matter would help me a lot. Thanks again!

**Comment by hchintalapudi** [comment]
I changed jq to absolute/path/jq in run_bulkModule.sh and the pipeline runs finally!
I've been getting other issues, checking logs and changing things. I'll do some more trial runs.

Thanks for your help!

**Comment by fl-yu** [comment]
Yes that is the issue of the genome path. It should work after remove the 'genome'.
If you follow my tutorial to download the reference genome, the genome file with FASTA format should have the same name (genome.fa) for different genome versions (hg19 or hg38). If users use their own data, sometimes the rule of naming is different which can cause the problem.

**Comment by hchintalapudi** [comment]
Hi,
I'm having issues with the MEME analysis for de novo motif finding.
Could you help me with what the issue is?

Thanks for the amazing tool!
[slurm-97220.out.txt](https://github.com/fl-yu/CUT-RUNTools-2.0/files/6791762/slurm-97220.out.txt)
