### ISSUE TITLE
MEME-chip error

### ISSUE THREAD

**Issue by TsviyaOlender** [fl-yu/CUT-RUNTools-2.0#27]
Hi
I downloaded the tool and installed it following your instructions, including MEME, which is installed in my home directory. I get the following error when CUT-RUN-Tools runs MEME:
[](url)I get an error when I try to cut the tool.

Unknown option: dreme-m
The sequences specified do not exist.

meme-chip [options] [-db <motif file>]* <primary sequence file>

 Options:
  -o                <dir>   : output to the specified directory, failing if the directory exists
  -oc               <dir>   : output to the specified directory, overwriting if the directory exists

Indeed, I checked and meme-chip doesn't have this option (also in the online manual).

What am I doing wrong? Should I also download MEME databases? I didn't see the databases in the installation.

Thanks
Tsviya

**Comment by TsviyaOlender** [comment]
Hi
Sorry for the delay in the response. I am using python 3.7.0

**Comment by baijiexu** [comment]
Hi Fulong,

Actually, I faced the same problem with MEME analysis.

```
[info] Start MEME analysis for de novo motif finding ...
[info] Up to 10 will be output ...
Log::Log4perl configuration looks suspicious: No loggers defined at /home2/s207732/anaconda3/envs/meme/lib/site_perl/5.26.2/Log/Log4perl/Config.pm line 325.
Starting getsize: getsize random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa 1> $metrics
getsize ran successfully in 0.008416 seconds
Starting fasta-most: fasta-most -min 50 < random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa 1> $metrics
fasta-most ran successfully in 0.057853 seconds
Starting fasta-center: fasta-center -dna -len 100 < random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa 1> random1000/MEME_GATA1_D7_30min_chr11_shuf/seqs-centered
fasta-center ran successfully in 0.070102 seconds
Starting fasta-shuffle-letters: fasta-shuffle-letters random1000/MEME_GATA1_D7_30min_chr11_shuf/seqs-centered random1000/MEME_GATA1_D7_30min_chr11_shuf/seqs-shuffled -kmer 2 -tag -dinuc -dna -seed 1
fasta-shuffle-letters ran successfully in 0.008486 seconds
Starting fasta-get-markov: fasta-get-markov -nostatus -nosummary -dna -m 1 random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa random1000/MEME_GATA1_D7_30min_chr11_shuf/background
fasta-get-markov ran successfully in 0.007927 seconds
Starting meme: meme random1000/MEME_GATA1_D7_30min_chr11_shuf/seqs-centered -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out -mod zoops -nmotifs 10 -minw 6 -maxw 30 -bfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background -dna -revcomp -nostatus
meme ran successfully in 119.638589 seconds
Starting dreme: dreme -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/dreme_out -png -dna -p random1000/MEME_GATA1_D7_30min_chr11_shuf/seqs-centered -n random1000/MEME_GATA1_D7_30min_chr11_shuf/seqs-shuffled -m 10
  File "/home2/s207732/anaconda3/envs/meme/bin/dreme", line 765
    print "Finding secondary RE in left flank..."
                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Finding secondary RE in left flank...")?
dreme exited with error code 1
Starting centrimo: centrimo -seqlen 201 -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/centrimo_out -bfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
FATAL: Template does not contain data section.

centrimo exited with error code 1
Starting tomtom: tomtom -verbosity 1 -text -thresh 0.1 random1000/MEME_GATA1_D7_30min_chr11_shuf/combined.meme random1000/MEME_GATA1_D7_30min_chr11_shuf/combined.meme 1> random1000/MEME_GATA1_D7_30min_chr11_shuf/motif_alignment.txt
tomtom ran successfully in 1.166558 seconds
Starting spamo: spamo -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/spamo_out_1 -bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background -keepprimary -primary GTGTAGTATCTGTTCTTATCAGTTTAA random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml
spamo exited with error code 1
Starting spamo: spamo -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/spamo_out_2 -bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background -keepprimary -primary TCTGATACGTCCTCTATCCGAGGACAATAT random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml
spamo exited with error code 1
Starting spamo: spamo -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/spamo_out_3 -bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background -keepprimary -primary TCGCTTCTCGGCCTTTTGGCTAAGATCAA random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml
spamo exited with error code 1
Starting spamo: spamo -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/spamo_out_4 -bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background -keepprimary -primary ATTAAATGGATTTTTGGAAST random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml
spamo exited with error code 1
Starting spamo: spamo -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/spamo_out_5 -bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background -keepprimary -primary TCAAAGTKAARAARWWCWATGAAGMGMGRG random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml
spamo exited with error code 1
Starting spamo: spamo -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/spamo_out_6 -bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background -keepprimary -primary GATSACVMGGYATWTKGCYASMTTRWGRGA random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml
spamo exited with error code 1
Starting fimo: fimo --parse-genomic-coord --verbosity 1 --oc random1000/MEME_GATA1_D7_30min_chr11_shuf/fimo_out_1 --bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background --motif GTGTAGTATCTGTTCTTATCAGTTTAA random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa
fimo ran successfully in 0.078399 seconds
Starting fimo: fimo --parse-genomic-coord --verbosity 1 --oc random1000/MEME_GATA1_D7_30min_chr11_shuf/fimo_out_2 --bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background --motif TCTGATACGTCCTCTATCCGAGGACAATAT random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa
fimo ran successfully in 0.0623 seconds
Starting fimo: fimo --parse-genomic-coord --verbosity 1 --oc random1000/MEME_GATA1_D7_30min_chr11_shuf/fimo_out_3 --bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background --motif TCGCTTCTCGGCCTTTTGGCTAAGATCAA random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa
fimo ran successfully in 0.057511 seconds
Starting fimo: fimo --parse-genomic-coord --verbosity 1 --oc random1000/MEME_GATA1_D7_30min_chr11_shuf/fimo_out_4 --bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background --motif ATTAAATGGATTTTTGGAAST random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa
fimo ran successfully in 0.057701 seconds
Starting fimo: fimo --parse-genomic-coord --verbosity 1 --oc random1000/MEME_GATA1_D7_30min_chr11_shuf/fimo_out_5 --bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background --motif TCAAAGTKAARAARWWCWATGAAGMGMGRG random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa
fimo ran successfully in 0.060443 seconds
Starting fimo: fimo --parse-genomic-coord --verbosity 1 --oc random1000/MEME_GATA1_D7_30min_chr11_shuf/fimo_out_6 --bgfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background --motif GATSACVMGGYATWTKGCYASMTTRWGRGA random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa
fimo ran successfully in 0.061917 seconds
Starting meme-chip_html_to_tsv: meme-chip_html_to_tsv random1000/MEME_GATA1_D7_30min_chr11_shuf/meme-chip.html random1000/MEME_GATA1_D7_30min_chr11_shuf/summary.tsv "meme-chip -oc random1000/MEME_GATA1_D7_30min_chr11_shuf -dreme-m 10 -meme-nmotifs 10 random1000/padded.fa/GATA1_D7_30min_chr11_summits_padded.fa" 5.0.5 "Mon Mar 18 20\:12\:19 2019 -0700"
meme-chip_html_to_tsv ran successfully in 0.132562 seconds
[info] De Novo motifs can be found: random1000/MEME_GATA1_D7_30min_chr11_shuf ...
[info] Loading the De Novo motifs ...
Traceback (most recent call last):
  File "/home2/s207732/CUT_RUNTools-2.0/install/read.meme.py", line 94, in <module>
    dreme_matrices = read_dreme(this_dir + "/dreme_out/dreme.txt")
  File "/home2/s207732/CUT_RUNTools-2.0/install/read.meme.py", line 47, in read_dreme
    f = open(n)
FileNotFoundError: [Errno 2] No such file or directory: 'random1000/MEME_GATA1_D7_30min_chr11_shuf/dreme_out/dreme.txt'
[info] The signficance cutoff of Fimo scaning is 0.0005...
[info] Motif files can be found: random1000/MEME_GATA1_D7_30min_chr11_shuf/motifs
[info] Filtering the blacklist regions for the selected peak files
[info] Getting Fasta sequences
Warning: the index file is older than the FASTA file.
[info] Scaning the De Novo motifs for each peak
ls: cannot access random1000/MEME_GATA1_D7_30min_chr11_shuf/motifs: No such file or directory
[info] Output can be found: fimo.result/GATA1_D7_30min_chr11
#
#        Congrats! The bulk data analysis is complete!
#
--------------------------------------------------------------------------
```
 
However, I could get the folder for MEME.

![image](https://user-images.githubusercontent.com/109556339/180850580-a4a72939-e503-47ed-82b7-511212a46ec1.png)

Here is the versions of meme and python. I created a separate environment for MEME as you suggested. 
```
meme -version
5.0.5
```
```
python --version
Python 3.7.12
```

Many thanks, 
Baijie
