### ISSUE TITLE
dreme problem

### ISSUE THREAD

**Issue by yannnnLi** [fl-yu/CUT-RUNTools-2.0#32]
Hello Fulong，I am runing the pipeline using the example data.
I got the strand error from the computing cluster when I run the command "run_bulkModule.sh ../CUT-RUNTools-2.0/config/bulk-config.json GATA1_D7_30min_chr11":

......
_**Starting dreme: dreme -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/dreme_out -png -dna -p random1000/MEME_GATA1_D7_30mi
n_chr11_shuf/seqs-centered -n random1000/MEME_GATA1_D7_30min_chr11_shuf/seqs-shuffled -m 10
  File "/public/home/liunangroup/liangyan/miniconda3/envs/meme/bin/dreme", line 765
    print "Finding secondary RE in left flank...
                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Finding secondary RE in left flank...")?
dreme exited with error code 1**_
Starting centrimo: centrimo -seqlen 201 -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/centrimo_out -bfile random1000/MEME_GATA1_D7_30min_chr11_shuf/background random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa random1000/MEME_GATA1_D7_30min_chr11_shuf/meme_out/meme.xml
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
FATAL: Template does not contain data section.

centrimo exited with error code 1
Starting tomtom: tomtom -verbosity 1 -text -thresh 0.1 random1000/MEME_GATA1_D7_30min_chr11_shuf/combined.meme random1000/MEME_GATA1_D7_30min_chr11_shuf/combined.meme 1> random1000/MEME_GATA1_D7_30min_chr11_shuf/motif_alignment.txt
tomtom ran successfully in 0.103372 seconds
......

Additionally, I get this strand output:

......
ri Dec 24 13:43:02 CST 2021
[info] Your bigwig file won't be normalized with spike-in reads
[info] Input file is /public/home/liunangroup/liangyan/pipeline/CUT-RUNTest/GATA1_D7_30min_chr11/peakcalling/macs2.narrow/GATA1_D7_30min_chr11_peaks.narrowPeak
[info] Get randomized [1000] peaks from the top [2000] peaks...
[info] Filtering the blacklist regions for the selected peak files
[info] Getting Fasta sequences
[info] Start MEME analysis for de novo motif finding ...
[info] Up to 10 will be output ...
_**Log::Log4perl configuration looks suspicious: No loggers defined at /public/home/liunangroup/liangyan/miniconda3/envs/meme/lib/site_perl/5.26.2/Log/Log4perl/Config.pm line 325.
[info] De Novo motifs can be found: random1000/MEME_GATA1_D7_30min_chr11_shuf ...
[info] Loading the De Novo motifs ...
Traceback (most recent call last):
  File "/public/home/liunangroup/liangyan/pipeline/CUT-RUNTools-2.0/install/read.meme.py", line 94, in <module>
    dreme_matrices = read_dreme(this_dir + "/dreme_out/dreme.txt")
  File "/public/home/liunangroup/liangyan/pipeline/CUT-RUNTools-2.0/install/read.meme.py", line 47, in read_dreme
    f = open(n)
FileNotFoundError: [Errno 2] No such file or directory: 'random1000/MEME_GATA1_D7_30min_chr11_shuf/dreme_out/dreme.txt'**_
[info] The signficance cutoff of Fimo scaning is 0.0005...
[info] Motif files can be found: random1000/MEME_GATA1_D7_30min_chr11_shuf/motifs
[info] Filtering the blacklist regions for the selected peak files
[info] Getting Fasta sequences
[info] Scaning the De Novo motifs for each peak
ls: cannot access random1000/MEME_GATA1_D7_30min_chr11_shuf/motifs: No such file or directory
[info] Output can be found: fimo.result/GATA1_D7_30min_chr11
......

I think the problem is in the text I marked, but how should I deal with it?
Thanks Yan.

**Comment by yannnnLi** [comment]
This problem has been solved based on the issue: https://github.com/fl-yu/CUT-RUNTools-2.0/issues/20 .
