### ISSUE TITLE
Samview failed to read header

### ISSUE THREAD

**Issue by PatrickMaclean** [fl-yu/CUT-RUNTools-2.0#50]
Hi - thank you for making your software available to use.

I'm having trouble running the bulk example data, where I receive the error 'samview failed to read header' during the early part of the pipeline. The intermediate file /~output-folder/aligned/GATA1_D7_30min.bam is empty. 

Is this an issue you've seen before? I am running the pipeline with your premade conda environment on an SGE computing cluster.

 Full code below - thank you

```
(cutruntools2) [qmy094@rescomp1 CUT-RUNTools-2.0]$ ./run_bulkModule.sh /well/jknight/users/qmy094/software/CUT-RUNTools-2.0/JSONs/testconfig.json GATA1_D7_30min
==================================== Bulk data analysis pipeline will run ==============================================================
## Input FASTQ folder:            /well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData
## Sample name:                   GATA1_D7_30min
## Workdir folder:                /well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output/GATA1_D7_30min
## Experiment name:               GATA1_D7_30min
## Experiment type:               CUT&RUN
## Reference genome:              hg38
## Spike-in genome:               FALSE
## Spike-in normalization:        FALSE
## Fragment 120 filtration:       TRUE
=================================================================================================================================
[info] Input file is GATA1_D7_30min_R1_001.fastq.gz and GATA1_D7_30min_R2_001.fastq.gz
Wed Jun 22 15:56:37 BST 2022
[info] Trimming file GATA1_D7_30min ...
Wed Jun 22 15:56:37 BST 2022
[info] Use Truseq adaptor as default 
[info] Second stage trimming GATA1_D7_30min ...
Wed Jun 22 15:56:38 BST 2022
[info] Aligning file GATA1_D7_30min to reference genome...
Wed Jun 22 15:56:38 BST 2022
[info] Bowtie2 command: --dovetail --phred33
[info] The dovetail mode is enabled [as parameter frag_120 is on]
[main_samview] fail to read the header from "-".
[info] FASTQ files won't be aligned to the spike-in genome
[info] Filtering unmapped fragments... GATA1_D7_30min.bam
Wed Jun 22 15:56:39 BST 2022
[main_samview] fail to read the header from "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output/GATA1_D7_30min/aligned/GATA1_D7_30min.bam".
[info] Sorting BAM... GATA1_D7_30min.bam
Wed Jun 22 15:56:39 BST 2022
INFO    2022-06-22 15:56:40     SortSam

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    SortSam -INPUT sorted/GATA1_D7_30min.step1.bam -OUTPUT sorted/GATA1_D7_30min.bam -SORT_ORDER coordinate -VALIDATION_STRINGENCY SILENT
**********


15:56:40.407 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gpfs2/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install/picard-2.8.0.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Jun 22 15:56:40 BST 2022] SortSam INPUT=sorted/GATA1_D7_30min.step1.bam OUTPUT=sorted/GATA1_D7_30min.bam SORT_ORDER=coordinate VALIDATION_STRINGENCY=SILENT    VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Jun 22 15:56:40 BST 2022] Executing as qmy094@rescomp1.hpc.in.bmrc.ox.ac.uk on Linux 3.10.0-1160.66.1.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_172-b11; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.21.7-SNAPSHOT
INFO    2022-06-22 15:56:40     SortSam Finished reading inputs, merging and writing to output now.
[Wed Jun 22 15:56:40 BST 2022] picard.sam.SortSam done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2058354688
[info] Marking duplicates... GATA1_D7_30min.bam
Wed Jun 22 15:56:40 BST 2022
[info] Removing duplicates... GATA1_D7_30min.bam
Wed Jun 22 15:56:49 BST 2022
[info] Filtering to <120bp... dup.marked and dedup BAMs
Wed Jun 22 15:56:49 BST 2022
[info] Creating bam index files... GATA1_D7_30min.bam
Wed Jun 22 15:56:49 BST 2022
[info] Reads shifting 
Wed Jun 22 15:56:49 BST 2022
[info] Your data won't be shifted as the experiment_type is specified as CUT&RUN... 
[info] Peak calling using MACS2... GATA1_D7_30min.bam
[info] Logs are stored in /well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output/GATA1_D7_30min/logs
Wed Jun 22 15:56:49 BST 2022
[info] Peak calling with BAM file with NO duplications
[info] macs2 narrow peak calling
[info] macs2 broad peak calling
[info] Getting broad peak summits
Traceback (most recent call last):
  File "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install/get_summits_broadPeak.py", line 14, in <module>
    f = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: '/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output/GATA1_D7_30min/peakcalling/macs2.broad/GATA1_D7_30min_peaks.broadPeak'
[info] SEACR stringent peak calling
Traceback (most recent call last):
  File "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install/change.bdg.py", line 12, in <module>
    f = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: '/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output/GATA1_D7_30min/peakcalling/seacr/GATA1_D7_30min_treat_pileup.bdg'
Calling enriched regions without control file
Proceeding without normalization of control to experimental bedgraph
Using stringent threshold
Creating experimental AUC file: Wed Jun 22 15:57:01 BST 2022
Calculating optimal AUC threshold: Wed Jun 22 15:57:01 BST 2022
Using user-provided threshold: Wed Jun 22 15:57:01 BST 2022
Error in read.table(argsL$exp) : no lines available in input
Execution halted
Unable to access /well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output/GATA1_D7_30min/peakcalling/seacr/GATA1_D7_30min_treat.stringent.bed
Traceback (most recent call last):
  File "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install/get_summits_seacr.py", line 14, in <module>
    f = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: '/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output/GATA1_D7_30min/peakcalling/seacr/GATA1_D7_30min_treat.stringent.bed'
[info] Generating the normalized signal file with BigWig format... 
Wed Jun 22 15:57:03 BST 2022
cp: cannot stat '/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output/GATA1_D7_30min/peakcalling/macs2.narrow/GATA1_D7_30min.cpm.norm.bw': No such file or directory
cp: cannot stat '/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output/GATA1_D7_30min/peakcalling/macs2.narrow/GATA1_D7_30min.cpm.norm.bw': No such file or directory
[info] Your bigwig file won't be normalized with spike-in reads
[info] Input file is /well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output/GATA1_D7_30min/peakcalling/macs2.narrow/GATA1_D7_30min_peaks.narrowPeak
cat: GATA1_D7_30min_peaks.narrowPeak: No such file or directory
cat: GATA1_D7_30min_summits.bed: No such file or directory
[info] Get randomized [1000] peaks from the top [2000] peaks...
[info] Filtering the blacklist regions for the selected peak files
[info] Getting Fasta sequences
Warning: the index file is older than the FASTA file.
[info] Start MEME analysis for de novo motif finding ...
[info] Up to 10 will be output ...
Log::Log4perl configuration looks suspicious: No loggers defined at /gpfs2/well/jknight/users/qmy094/software/conda/skylake/envs/meme/lib/site_perl/5.26.2/Log/Log4perl/Config.pm line 325.
Starting getsize: getsize random1000/MEME_GATA1_D7_30min_shuf/GATA1_D7_30min_summits_padded.fa 1> $metrics
getsize ran successfully in 0.043017 seconds
Starting fasta-most: fasta-most -min 50 < random1000/MEME_GATA1_D7_30min_shuf/GATA1_D7_30min_summits_padded.fa 1> $metrics
fasta-most ran successfully in 0.499825 seconds
Starting fasta-center: fasta-center -dna -len 100 < random1000/MEME_GATA1_D7_30min_shuf/GATA1_D7_30min_summits_padded.fa 1> random1000/MEME_GATA1_D7_30min_shuf/seqs-centered
fasta-center ran successfully in 0.142205 seconds
Starting fasta-shuffle-letters: fasta-shuffle-letters random1000/MEME_GATA1_D7_30min_shuf/seqs-centered random1000/MEME_GATA1_D7_30min_shuf/seqs-shuffled -kmer 2 -tag -dinuc -dna -seed 1
fasta-shuffle-letters ran successfully in 0.026512 seconds
Starting fasta-get-markov: fasta-get-markov -nostatus -nosummary -dna -m 1 random1000/MEME_GATA1_D7_30min_shuf/GATA1_D7_30min_summits_padded.fa random1000/MEME_GATA1_D7_30min_shuf/background
fasta-get-markov ran successfully in 0.034755 seconds
Starting meme: meme random1000/MEME_GATA1_D7_30min_shuf/seqs-centered -oc random1000/MEME_GATA1_D7_30min_shuf/meme_out -mod zoops -nmotifs 10 -minw 6 -maxw 30 -bfile random1000/MEME_GATA1_D7_30min_shuf/background -dna -revcomp -nostatus
No sequences found in file `random1000/MEME_GATA1_D7_30min_shuf/seqs-centered'.  Check file format.
meme exited with error code 1
Starting dreme: dreme -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_shuf/dreme_out -png -dna -p random1000/MEME_GATA1_D7_30min_shuf/seqs-centered -n random1000/MEME_GATA1_D7_30min_shuf/seqs-shuffled -m 10
  File "/well/jknight/users/qmy094/software/conda/skylake/envs/meme/bin/dreme", line 765
    print "Finding secondary RE in left flank..."
                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Finding secondary RE in left flank...")?
dreme exited with error code 1
Starting meme-chip_html_to_tsv: meme-chip_html_to_tsv random1000/MEME_GATA1_D7_30min_shuf/meme-chip.html random1000/MEME_GATA1_D7_30min_shuf/summary.tsv "meme-chip -oc random1000/MEME_GATA1_D7_30min_shuf -dreme-m 10 -meme-nmotifs 10 random1000/padded.fa/GATA1_D7_30min_summits_padded.fa" 5.0.5 "Mon Mar 18 20\:12\:19 2019 -0700"
meme-chip_html_to_tsv ran successfully in 0.819111 seconds
[info] De Novo motifs can be found: random1000/MEME_GATA1_D7_30min_shuf ...
[info] Loading the De Novo motifs ...
Traceback (most recent call last):
  File "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install/read.meme.py", line 94, in <module>
    dreme_matrices = read_dreme(this_dir + "/dreme_out/dreme.txt")
  File "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install/read.meme.py", line 47, in read_dreme
    f = open(n)
FileNotFoundError: [Errno 2] No such file or directory: 'random1000/MEME_GATA1_D7_30min_shuf/dreme_out/dreme.txt'
[info] The signficance cutoff of Fimo scaning is 0.0005...
[info] Motif files can be found: random1000/MEME_GATA1_D7_30min_shuf/motifs
[info] Filtering the blacklist regions for the selected peak files
[info] Getting Fasta sequences
Warning: the index file is older than the FASTA file.
[info] Scaning the De Novo motifs for each peak
ls: cannot access random1000/MEME_GATA1_D7_30min_shuf/motifs: No such file or directory
[info] Output can be found: fimo.result/GATA1_D7_30min
# 
#        Congrats! The bulk data analysis is complete!
```

and here is my config.json
```
{
    "software_config": {
        "Rscriptbin": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin", 
        "pythonbin": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin", 
        "perlbin": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin",
        "javabin": "/apps/well/java/jdk1.8.0_latest/bin",
        "bowtie2bin": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin", 
        "samtoolsbin": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin", 
        "macs2bin": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin", 
        "memebin": "/well/jknight/users/qmy094/software/conda/skylake/envs/meme/bin", 
        "bedopsbin": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin", 
        "bedtoolsbin": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin", 
        "path_deeptools": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin",
        "path_parallel": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin", 
        "path_tabix": "/well/jknight/users/qmy094/software/conda/skylake/envs/cutruntools2/bin",
        "bt2idx": "/gpfs2/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install/assemblies/hg38", 
        "genome_sequence": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install/assemblies/hg38/hg38.fa", 
        "spike_in_bt2idx": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/assemblies/Escherichia_coli_K_12_DH10B", 
        "spike_in_sequence": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/assemblies/Escherichia_coli_K_12_DH10B/Escherichia_coli_K_12_DH10B.fna", 
        "extratoolsbin": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install", 
        "extrasettings": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install",
        "kseqbin": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install", 
        "adapterpath": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/adapters", 
        "trimmomaticbin": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install", 
        "picardbin": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install", 
        "picardjarfile": "picard-2.8.0.jar", 
        "trimmomaticjarfile": "trimmomatic-0.36.jar", 
        "makecutmatrixbin": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/install"
    }, 
    "input_output": {
        "fastq_directory": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData", 
        "workdir": "/well/jknight/users/qmy094/software/CUT-RUNTools-2.0/exampleData/output", 
        "fastq_sequence_length": "42", 
        "organism_build": "hg38",
        "spike_in": "FALSE",
        "spike_in_norm": "FALSE",
        "spikein_scale": "10000",
        "frag_120": "TRUE",
        "peak_caller": "macs2",
        "dup_peak_calling": "FALSE",
        "cores": "8",
        "experiment_type": "CUT&RUN"
    }, 
    "motif_finding": {
        "num_bp_from_summit": "100", 
        "num_peaks": "1000", 
        "total_peaks": "2000", 
        "motif_scanning_pval": "0.0005", 
        "num_motifs": "10"
    }
}
```

**Comment by fl-yu** [comment]
I will close this thread but please feel free to reopen it if you have questions.
