### ISSUE TITLE
Please improve error reporting with 'validate.py'

### ISSUE THREAD

**Issue by rmarable** [fl-yu/CUT-RUNTools-2.0#53]
When running `validate.py` against a non-existing configuration file, the following output is returned:
```
./validate.py --ignore-input-output --software bulk-config2.json
Traceback (most recent call last):
  File "./validate.py", line 41, in <module>
    args = vars(parser.parse_args(sys.argv[1:]))
  File "/usr/lib64/python2.7/argparse.py", line 1705, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1737, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1946, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib64/python2.7/argparse.py", line 1902, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python2.7/argparse.py", line 1795, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib64/python2.7/argparse.py", line 2235, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib64/python2.7/argparse.py", line 2264, in _get_value
    result = type_func(arg_string)
IOError: [Errno 2] No such file or directory: 'bulk-config2.json'
```
It would be great if this `IOError` could be properly trapped so the script returns more descriptive output.
```
./validate.py --ignore-input-output --software bulk-config2.json
***ERROR***
Missing configuration file: bulk-config2.json
```

**Comment by fl-yu** [comment]
Thank you for your feedback! this seems to be an improvement rather than a bug. I am really tied up with other work. I wonder that would you like to contribute to this as a contributor? That would be awesome!
