### ISSUE TITLE
meme problen：Failed to create PNG file；make_cut_matrix mistake

### ISSUE THREAD

**Issue by Zhiyi-Chen17** [fl-yu/CUT-RUNTools-2.0#78]
hi，fulong，"I am facing an issue with DREME3-py where I cannot generate PNG files properly, while other files can be generated successfully. Additionally, my ATACtk is not running as expected."

Starting meme: meme random1000/MEME_PRDM9_shuf/seqs-centered -oc random1000/MEME_PRDM9_shuf/meme_out -mod zoops -nmotifs 10 -minw 6 -maxw 30 -bfile random1000/MEME_PRDM9_shuf/background -dna -revcomp -nostatus
meme ran successfully in 2570.817556 seconds
Starting dreme-py3: dreme-py3 -verbosity 1 -oc random1000/MEME_PRDM9_shuf/dreme_out -png -dna -p random1000/MEME_PRDM9_shuf/seqs-centered -n random1000/MEME_PRDM9_shuf/seqs-shuffled -m 10
Failed to create PNG file. Have you got ghostscript installed?
Failed to create PNG file. Have you got ghostscript installed?
Failed to create PNG file. Have you got ghostscript installed?
Failed to create PNG file. Have you got ghostscript installed?
Failed to create PNG file. Have you got ghostscript installed?
Failed to create PNG file. Have you got ghostscript installed?

-------------------------
[info] Doing fimo2.DREME-10.AHCTAAAC...
make_cut_matrix -v -b '(25-150 1)' -d -o 0 -r 100 -p 1 -f 3 -F 4 -F 8 -q 0 /media/dell/data2/chenzhiyi/23.11.3_wangbingyi/output/BN-2/aligned/dup.marked.120bp/BN-2.bam  /media/dell/data2/chenzhiyi/23.11.3_wangbingyi/output/BN-2/peakcalling/macs2.narrow/BN-2_summits.bed > fimo.cuts.freq.txt
Traceback (most recent call last):
  File "/home/chenzhiyi/.local/bin/make_cut_matrix", line 277, in <module>
    make_cut_matrix(parse_arguments())
  File "/home/chenzhiyi/.local/bin/make_cut_matrix", line 182, in parse_arguments
    return parser.parse_args()
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 1824, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 2265, in _get_values
    value = self._get_value(action, arg_string)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 2294, in _get_value
    result = type_func(arg_string)
  File "/home/chenzhiyi/.local/lib/python3.6/site-packages/atactk/command.py", line 126, in parse_bins
    bin_string = bin_string.value()
AttributeError: 'Symbol' object has no attribute 'value'

**Comment by zyyyyy11144** [comment]
"For the issue of being unable to create PNG files, I found that changing the output format of DREME3 from `-png` to `-eps` resolved the problem. 
For the problem of not being able to generate `fimo.cuts.freq.txt`, when I use ATACtk installed directly from the official website without applying any patches, the program runs successfully."
